Marked sendmail as suggested package and added check in the script if it is installed when trying to send email.

diff --git a/src/bash/files-backup b/src/bash/files-backup
--- a/src/bash/files-backup
+++ b/src/bash/files-backup
@@ -112,6 +112,12 @@ checkVariable DIR
 
 if [[ "$SEND_MAIL" == true ]]; then
   checkVariable EMAILTO
+
+  # Check if sendmail is installed
+  if ! which sendmail > /dev/null; then
+    echo "Error: sendmail is not installed on this system."
+    exit 1
+  fi
 fi
 
 # DATE format
